version: '3.0'
services:
  database:
    image: mongo
    ports:
      - '27017:27017'

  loopback:
    build: .
    ports:
      - '8080:8080' # specify port mapping
    links:
      - database # link this service to the database service
